### ISSUE TITLE
Sql Tables

### ISSUE THREAD

**Issue by cnccld** [Dutchy-/gitolite_mysqlgenerator#1]
I'ts possible to provide an .sql file or the tables structure?

Regards
Claudio

**Comment by Dutchy-** [comment]
I want to give you structure, but I've been terribly busy. I think the structure could be understood from  the queries, but you could ofcourse just change the queries to fit your own structure.

Whenever I find some time, I will have a look at creating an .sql file, in the meanwhile I ofcourse accept pull requests to add it :)
